### ISSUE TITLE
Question on benchmarking GPT-4V

### ISSUE THREAD

**Issue by jeasinema** [X2FD/LVIS-INSTRUCT4V#1]
Hi,

Thanks for this inspiring project. I have one quick question regarding the usage of GPT-4V here: have you tried to evaluate GPT-4V directly on the selected benchmarks, say GQA, SEED, etc? If so, what are the results? Indeed, this could give us a better sense of how capable GPT-4V is at this point and support the visual instruction tuning.

Best,
XM

**Comment by wdrink** [comment]
Hi, thanks for your interest in our work. Actually, evaluating the performance of GPT-4V on these benchmarks is indeed interesting and could function as a strong baseline. As far as we know, several benchmarks have already implemented this, please refer to their leaderboard for detailed numbers (https://github.com/BradyFU/Awesome-Multimodal-Large-Language-Models/tree/Evaluation). Have a good day!
