### ISSUE TITLE
How did you got past 100 RPD?

### ISSUE THREAD

**Issue by chavinlo** [X2FD/LVIS-INSTRUCT4V#2]
A bit off-topic, but how did you managed to get past the 100 Requests Per Day limit imposed by the API?

**Comment by HenryHZY** [comment]
Same question.

**Comment by echo840** [comment]
Same question.

**Comment by Labmem009** [comment]
Maybe it takes many accounts and many days......

**Comment by echo840** [comment]
But the API for GPT-4V only started to be available from November 7th.

**Comment by chavinlo** [comment]
Thye could have also automated the process using only CGPT+ Accounts

**Comment by Etelis** [comment]
220K instructions mean about 314 accounts (220,000 / (100 * 7)) – that's a lot of SIMs.  Got any proof of actually doing this? Seems like they'd use LLAVA, not GPT-4V. 

And this calculation is if they started the moment the API came out, which I do not belive as they needed to do a bit testing before.. this means they had about 500 accounts ready with credits.. (as GPT4V requires at least $5 investment) so you also had like 100 credit cards? or maybe you used one credit card 500 times..

**Comment by wdrink** [comment]
We did not get past the restriction. The instruction data are generated by GPT-4V (if you carefully examine the data, you will notice that they contain a lot of details that do not exist in LLaVA). We believe that using harsh words like “stink” is not helpful for a discussion. We are closing this issue as it is indeed a bit “off-topic”

**Comment by chavinlo** [comment]
> We did not get past the restriction. The instruction data are generated by GPT-4V (if you carefully examine the data, you will notice that they contain a lot of details that do not exist in LLaVA). We believe that using harsh words like “stink” is not helpful for a discussion. We are closing this issue as it is indeed a bit “off-topic”

Thanks, but I was asking which method did you used to access GPT4 Vision (Official API?, ChatGPT Plus?). I was planning on using an account swarm too, so no shame in that.

**Comment by chavinlo** [comment]
> 220K instructions mean about 314 accounts (220,000 / (100 * 7)) – that's a lot of SIMs and sounds like a breach of OpenAI's rules. 🤔 Got any proof of actually doing this? Seems like they'd use LLAVA, not GPT-4V.
> 
> And this calculation is if they started the moment the API came out, which I do not belive as they needed to do a bit testing before.. this means they had about 500 accounts ready with credits.. (as GPT4V requires at least $5 investment) so you also had like 100 credit cards? or maybe you used one credit card 500 times.. Give me a break this stinks!!!

Kill yourself fag
