### ISSUE TITLE
Nice Work！ Question about caption

### ISSUE THREAD

**Issue by BlueBlueFF** [X2FD/LVIS-INSTRUCT4V#4]
LVIS dataset only have category and bbox info，do you use caption(from coco) in generate instrutions？

**Comment by wdrink** [comment]
No, for the conversational question-answer data, we only feed GPT-4V with the image (as well as a carefully designed prompt); while for the high-quality image descriptions, we input both the image and its box annotations in LVIS (prompt also) to GPT-4V. Please refer to the _Appendix_ of our arXiv paper (https://arxiv.org/abs/2311.07574) for more details.
