### ISSUE TITLE
Schedule of releasing 13B checkpoint.

### ISSUE THREAD

**Issue by HenryHZY** [X2FD/LVIS-INSTRUCT4V#5]
Hi @wangjk666 , thanks for your great project. I have tried the 7B checkpoint and it works well.

I would like to ask if you have a plan to release the 13B checkpoint? I understand that uploading the checkpoint to huggingface repo does take some time:)

**Comment by wdrink** [comment]
Hi, thanks for your interest in our work and positive feedback. The 13B models have already been released in [Hugging Face](https://huggingface.co/X2FD), feel free to download them and have a try.
