### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by zhaoyuzhi** [X2FD/LVIS-INSTRUCT4V#8]
Thanks for your work. However, when I test your model using LLaVA code, I encounter this problem:

File "/home/zyz//inference_llava.py", line 119, in main
image_tensor = image_processor.preprocess(image, return_tensors='pt')['pixel_values'].half().cuda()
AttributeError: 'NoneType' object has no attribute 'preprocess'

When I load a LLaVA v1.5 model, there is no error. I have checked the "image" is a valid PIL.Image object. Could you please check why there is an AttributeError? Thanks.

**Comment by wdrink** [comment]
Hi, please refer to this [issue](https://github.com/haotian-liu/LLaVA/issues/444) in the LLaVA repo, you can modify the code to load a pretrained model, or rename the checkpoint dir.
