### ISSUE TITLE
typo of "LVIS-Instrcut4V + LLaVA-Instruct" checkpoint URL on README

### ISSUE THREAD

**Issue by Maxlinn** [X2FD/LVIS-INSTRUCT4V#9]
thanks for bringing about LVIS!

i found there is a slight typo on the README.md that, in the Model Zoo table, the Checkpoint of "LVIS-Instrcut4V" and "LVIS-Instrcut4V + LLaVA-Instruct" are both pointing to "https://huggingface.co/X2FD/LVIS-Instruct4v-13b", but i believe the latter should be pointing to "https://huggingface.co/X2FD/LVIS-Instruct4v-LLaVA-13b".

**Comment by wdrink** [comment]
Thanks for pointing this out, I have fixed the typo in the README~
